const data = {
   products: [
    {
      name: 'Itouch glasses 01',
      slug: 'Itouch01',
      category: 'Shirts',
      image: ('./images/p1.jpg'),
      price: 120,
      countInStock: 10,
      brand: 'Itouch',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Itouch glasses 02',
      slug: 'Itouch02',
      category: 'Shirts',
      image: ('./images/p8.jpg'),
      price: 250,
      countInStock: 20,
      brand: 'Itouch',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Itouch glasses 03',
      slug: 'Itouch03',
      category: 'Pants',
      image: ('./images/p4.jpg'),
      price: 25,
      countInStock: 15,
      brand: 'Itouch',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Itouch glasses 04',
      slug: 'Itouch04',
      category: 'Pants',
      image: ('./images/p5.jpg'),
      price: 65,
      countInStock: 5,
      brand: 'Itouch',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
module.exports= data;