const data = {
  products: [
    {
      name: 'Itouch glasses 01',
      slug: 'Itouch glasses 01',
      category: 'Shirts',
      image: require('./images/p1.jpg'), // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Itouch glasses 02',
      slug: 'Itouch glasses 02',
      category: 'Shirts',
      image: require('./images/p8.jpg'),
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Itouch glasses 03',
      slug: 'Itouch glasses 03',
      category: 'Pants',
      image: require('./images/p4.jpg'),
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Itouch glasses 04',
      slug: 'Itouch glasses 04',
      category: 'Pants',
      image: require('./images/p5.jpg'),
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;